### ISSUE TITLE
Update blaze-slider version to 1.8.0 

### ISSUE THREAD

**Issue by MananTank** [TotomInc/vue-blaze-slider#1]
blaze-slider@1.8.0 adds the resize observer feature to slider. It refreshes the slider on window resize.
Checkout this playground: https://codesandbox.io/s/blaze-slider-playground-ps0b9u

No code change required.

**Comment by TotomInc** [comment]
Thanks for reporting this, I've just published `vue-blaze-slider@0.1.1` which include `blaze-slider@1.8.0`.
